function Kl = lnls_calc_loss_Factor_from_wake(tau, wake, distr)

% Plus the potential well generated by the wake:
Wl = zeros(1,length(tau));
if isfield(wake.long,'general')
    Wl = interp1(wake.long.general.tau,wake.long.general.wake,tau,'linear',0);
end
if isfield(wake.long,'resonator')
    wr = wake.long.resonator.wr;
    Rs = wake.long.resonator.Rs;
    Q  = wake.long.resonator.Q;
    
    Ql = sqrt(Q.^2 - 1/4);
    wrl = wr .* Ql ./ Q;
    
    for ii=1:length(wr)
        phasor = exp(tau*(1i*wrl(ii)+wr(ii)/(2*Q(ii))));
        Wl = Wl - wr(ii)*Rs(ii)/Q(ii)*(real(phasor) + 1/(2*Ql)*imag(phasor));
    end
    ind = tau > 0;
    Wl(ind) = 0;
    ind = tau == 0;
    Wl(ind) = Wl(ind)/2;
end


V = conv(distr,Wl,'same')*(tau(2)-tau(1));
Kl = -trapz(tau,distr.*V);
