function Kx = lnls_calc_kick_factor_from_wake(tau, wake, distr)

% Plus the potential well generated by the wake:
Wl = zeros(1,length(tau));
if isfield(wake.dipo,'general')
    Wl = interp1(wake.dipo.general.tau,wake.dipo.general.wake,tau,'linear',0);
end
if isfield(wake.dipo,'resonator')
    wr = wake.dipo.resonator.wr;
    Rs = wake.dipo.resonator.Rs;
    Q  = wake.dipo.resonator.Q;
    betax = wake.dipo.resonator.beta;
    
    Ql = sqrt(Q.^2 - 1/4);
    wrl = wr .* Ql ./ Q;
    
    for ii=1:length(wr)
        phasor = exp(tau*(1i*wrl(ii)+wr(ii)/(2*Q(ii))));
        Wl = Wl - betax(ii)*wr(ii)*Rs(ii)/Ql(ii)*imag(phasor);
    end
    ind = tau >= 0;
    Wl(ind) = 0;
end

V = conv(distr,Wl,'same')*(tau(2)-tau(1));
Kx = -trapz(tau,distr.*V)/trapz(tau,distr)^2;